// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using simple.Data;

#nullable disable

namespace simple.Migrations
{
    [DbContext(typeof(simpleContext))]
<<<<<<<< Updated upstream:Migrations/20260111235453_ConsisteciaArchivos1.Designer.cs
    [Migration("20260111235453_ConsisteciaArchivos1")]
    partial class ConsisteciaArchivos1
========
    [Migration("20260112001107_CajaMigration1")]
    partial class CajaMigration1
>>>>>>>> Stashed changes:Migrations/20260112001107_CajaMigration1.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EjemploNubeArticulo.Models.ContabilidadUsuario", b =>
                {
                    b.Property<int>("CON_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CON_Id"));

                    b.Property<bool>("CON_Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CON_Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CON_Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CON_FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CON_Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CON_Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CON_Salario")
                        .HasColumnType("numeric");

                    b.Property<string>("CON_Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CON_Id");

                    b.ToTable("ContabilidadUsuarios");
                });

            modelBuilder.Entity("simple.Entidades.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Articulo");
                });

            modelBuilder.Entity("simple.Entidades.BecasEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BecaActiva")
                        .HasColumnType("boolean");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoEstudiante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInicioBeca")
                        .HasColumnType("date");

                    b.Property<decimal>("MontoMensualBeca")
                        .HasColumnType("numeric");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoBeca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BecasEstudiantes");
                });

            modelBuilder.Entity("simple.Entidades.BibliotecaLibro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("integer");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Editorial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BibliotecaLibros");
                });

            modelBuilder.Entity("simple.Entidades.ConsistenciaArchivo", b =>
                {
                    b.Property<int>("Id_Archivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Archivo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha_Creacion")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Archivo");

                    b.ToTable("ConsistenciaArchivos");
                });

            modelBuilder.Entity("simple.Entidades.ContabilidadFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Pagada")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ContabilidadFacturas");
                });

            modelBuilder.Entity("simple.Entidades.SecretariaGeneralDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("SecretariaGeneralDocumentos");
                });

            modelBuilder.Entity("simple.Models.CajaFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("date");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("CajaFacturas");
                });

            modelBuilder.Entity("simple.Models.ProduccionContenido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<bool>("EsPublicado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<string>("TipoFormato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProduccionContenidos");
                });
#pragma warning restore 612, 618
        }
    }
}
